### ISSUE TITLE
access API with python request

### ISSUE THREAD

**Issue by marmooli** [bitholla/hollaex-node-lib#22]
Hello,
I try to access private API data from Exir platform, which ist a derivate of hollaex. Could you please help me to find, what  I 
 do wrong with my aproach with Python 3.
If I run this, I get the msg "`Access Denied: Invalid API Signature`" --> something is wrong with my api-signature

the documentation of Exir API is:
[https://apidocs.exir.io/#introduction](https://apidocs.exir.io/#introduction)

Thank you

here an example code:

```
import time
import json
import hmac
import hashlib
import requests
from urllib.parse import urljoin, urlencode

API_KEY = '65e...'
SECRET_KEY = '3c3...'
BASE_URL = 'https://api.exir.io'

timestamp = str(int(time.time()+10))

headers = {
    'api-key': API_KEY,
    'api-expires': timestamp
}

PATH='/v1/user/orders'
params = {"symbol":"btc-irt"}
url = urljoin(BASE_URL, PATH)
string = 'GET/v1/user/orders'+timestamp+str(params)
print(string)
headers['api-signature'] = hmac.new(SECRET_KEY.encode('utf-8'), string.encode('utf-8'), hashlib.sha256).hexdigest()
r = requests.get(url, headers=headers, params=params)
data = r.json()
print(json.dumps(data, indent=2))
```

**Comment by abeikverdi** [comment]
This library is for nodejs and does not support python.

I had a quick look at your code regardless and looks like your params is off. You should pass that as a query string and that should also be in your path before your timestamp when you hash it. For simplicity try it without sending any symbol and see if that works.

**Comment by marmooli** [comment]
Thank you very much and sorry that I posted an issue in this library. I try it your suggestion
با سپاس فراوان
و روز شما بخیر

**Comment by marmooli** [comment]
we read in the documentation of hollaex (and although Exir):
```
Examples of strings being encoded:
GET request to https://api.exir.io/v1/user/balance that expires at 1575516146

GET/v1/user/balance1575516146

POST request to https://api.exir.io/v1/order that expires at 1575516146 with body {"symbol":"btc-usdt","side":"buy","size":0.001,"type":"market"}

POST/v1/order1583284849{"symbol":"btc-usdt","side":"buy","size":0.001,"type":"market"}
```
do I need really a query string?
Itryed another path without params and it functions:

```
API_KEY = '65e...'
SECRET_KEY = '3c3e...'
BASE_URL = 'https://api.exir.io'
timestamp = str(int(time.time()+10))
headers = {
    'api-key': API_KEY,
    'api-expires': timestamp
}
PATH='/v1/user'
params = None
url = urljoin(BASE_URL, PATH)
string = 'GET/v1/user'+timestamp
headers['api-signature'] = hmac.new(SECRET_KEY.encode('utf-8'), string.encode('utf-8'), hashlib.sha256).hexdigest()
r = requests.get(url, headers=headers, params=params)
data = r.json()
print(json.dumps(data, indent=2))
```
استاد از این که وقت شما را می‌گیرم بسیار شرمنده‌ام و از شما سپاسگزارم اگر راهنمایی بفرمایید

**Comment by abeikverdi** [comment]
You don't need query string for /user endpoint. The above code looks fine to me. It doesn't work?
What I said earlier is that if you want to pass a query string for certain endpoints it should be part of your string:
`string = '/v1/user/orders?symbol=abc-xyz'+timestamp`
